authors = ["Marco Congedo <marco.congedo@gmail.com>"]
<<<<<<< HEAD
version = "0.4.9"
=======
version = "0.5.1"
>>>>>>> dev

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
<<<<<<< HEAD
Documenter = "~0.25"
=======
Documenter = "0.25, 0.26, 0.27"
>>>>>>> dev
